version: '2'
services:
  swellrt:
    image: p2pvalue/swellrt:${SWELLRT_VERSION}
    hostname: swellrt
    restart: always
    depends_on:
      - mongo
    ports:
      - "0.0.0.0:9898:9898"
    volumes:
      - ./config:/usr/local/swellrt/config
    environment:
      MONGODB_HOST: "mongo"
  mongo:
    image: mongo:latest
    restart: always
  tagger:
    image: p2pvalue/teem-tag:v1.2
    ports:
      - "5000:5000"
    depends_on:
     - swellrt
    environment:
      TEEMTAG_USERNAME: "teemtag@local.net"
      TEEMTAG_PASSWORD: "teemtag"
      SWELLRT_HOST: "swellrt"


